spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: pgsa73@sandboxf3e65bb776bc41caacf3257e54232862.mailgun.org

jwt:
  secret: ${JWT_SECRET_BASE64}
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true