spring:
  application:
    name: chirp

  data:
    redis:
      host: "redis-13010.c10.us-east-1-4.ec2.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 13010
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
    username: postgres.reaacwztaqjpnocrmsrt
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-poll-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMib: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

jwp:
  secret: ${JWT_SECRET_BASE64}
  expiration-minutes: 15

chirp:
  email:
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30