spring:
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET_BASE64}
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  rate-limit:
    ip:
      apply-limit: true