spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: pgsa73@sandboxf3e65bb776bc41caacf3257e54232862.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true